### PR TITLE
Man page generation from Markdown

### PR DESCRIPTION
**Pull request by koernepr**
**This adds a new build dependency**: [pandoc](https://pandoc.org/) (available for Windows/Mac OS X/Linux etc.)

# Overview

This pull request introduces man page generation from Markdown files using pandoc; the commits ...

 1. convert the existing man pages to Markdown with pandoc extensions (verbatim conversion)
 2. adjust the infrastructure to generate the man pages during building and mark them for distribution

In case you're not happy with Markdown, the pandoc Markdown extensions or pandoc itself, alternative lightweight markup languages and converters could be:

 * reStructuredText/AsciiDoc/... using pandoc
 * reStructuredText using `rst2man` from [docutils](http://docutils.sourceforge.net/) (Python)
 * AsciiDoc using [Asciidoctor](http://asciidoctor.org/) ([man page documentation](http://asciidoctor.org/docs/user-manual/#man-pages)) (Ruby)

Converting the Markdown files to a different format should be relatively easy (I didn't test the alternatives though).

In case you don't want to add a build dependency for either of these, a compromise could be to make an exception and add the generated files to the sources.

# Documentation

General: [pandoc website](https://pandoc.org/), [pandoc's Markdown](https://pandoc.org/MANUAL.html#pandocs-markdown)

For 1.:

 * [input file for pandoc's man page](https://github.com/jgm/pandoc/blob/master/MANUAL.txt) (they additionally use templating, also see the [man directory](https://github.com/jgm/pandoc/tree/0c029e8258268c026fe3d968809a160eecda7428/man))
 * [Markdown man page example](http://hyperpolyglot.org/lightweight-markup#toc5)
 * pandoc Markdown extensions: [pandoc_title_block](https://pandoc.org/MANUAL.html#extension-pandoc_title_block), [definition_lists](https://pandoc.org/MANUAL.html#extension-definition_lists), [all_symbols_escapable](https://pandoc.org/MANUAL.html#extension-all_symbols_escapable)

For 2.:

 * [man page rule in pandoc's Makefile](https://github.com/jgm/pandoc/blob/0c029e8258268c026fe3d968809a160eecda7428/Makefile#L40)
 * [Markdown man page example](http://hyperpolyglot.org/lightweight-markup#toc5)
 * ([Automake: Man Pages](https://www.gnu.org/software/automake/manual/html_node/Man-Pages.html))

# Useful commands while modifying the man pages

Generating a man page and previewing it using `man -l`:

```shell
$ name='amsynth.1'
$ make data/$name && man -l data/$name
```

Round-tripping the Markdown file using `pandoc` to find characters missed to escape (seems to work - no guarantees though; also it replaces `\<` and `\>` by HTML entities):

```shell
$ # in data/
$ name='amsynth.1'
$ pandoc -s -f markdown -t markdown --wrap=preserve -o $name.md.rt $name.md
$ diff -u $name.md $name.md.rt
```

# Miscellaneous

I'll create a follow-up pull request with man page improvements as soon as this one has been merged (otherwise I'll integrate them into the existing files).

@nixxcode: Are build dependencies documented in plain text somewhere? I didn't find anything human-oriented to add pandoc to.

Installing the files is not yet supported (it wasn't supported before either). I could not get this to work for non-English man pages and don't know if it's worth the effort in case you're switching to CMake anyway. If my CMake experiments turn out well, I might be able to add CMake support for building and installing the files in the near future.

Regarding date/version information in the man page: who should update this, and when? Should (part of) it be inserted at build time? That's done for the version information in pandoc's man page for example, but slightly complicates things.

Edits: clarifications regarding pandoc Markdown extensions; improved pandoc round-tripping command

### CODE REVIEW

**Comment by nixxcode** [comment]
I like this change, markdown is a lot nicer to edit than the previous format.

@koernepr build dependencies are currently listed on the wiki page [BuildingFromSource](https://github.com/amsynth/amsynth/wiki/BuildingFromSource) which I will update.

**Comment by nixxcode** [comment]
Date and version information can be manually updated (when preparing a new release) for now if it's messy to automate.

FYI I was not planning a switch to CMake as the official build system - CMakeLists.txt is there for use with the [CLion IDE](https://www.jetbrains.com/clion/).

**Comment by koernepr** [comment]
As it turns out, adding version and date might be as simple as calling pandoc like

`pandoc -s -t man --variable date="$DATE_TO_USE" --variable footer="amsynth $VERSION_TO_USE" -o $@ $<`

making sure the values to insert are sane.

Documentation: [pandoc templates](https://pandoc.org/MANUAL.html#templates), [variables set by pandoc](https://pandoc.org/MANUAL.html#variables-set-by-pandoc) (for `date`), [variables for man pages](https://pandoc.org/MANUAL.html#variables-for-man-pages) (for `footer`)

For pandoc's man page, as far as I can tell, a more complicated method is used: The version is [determined at build time](https://github.com/jgm/pandoc/blob/0c029e8258268c026fe3d968809a160eecda7428/Makefile#L1) and [passed to the pandoc call](https://github.com/jgm/pandoc/blob/0c029e8258268c026fe3d968809a160eecda7428/Makefile#L45) for generating the man page, but they use a [custom template](https://github.com/jgm/pandoc/blob/0c029e8258268c026fe3d968809a160eecda7428/man/pandoc.1.template) containing the `version` variable instead of pandoc's default man page template. I don't know why they don't use the easier method described above; maybe they just did not update their man page generation process when new template functionality was added.

**Comment by koernepr** [comment]
Regarding the date, it might be a good idea to use a somewhat fixed one to support reproducible builds.

**Pull request merged**
